# Generated by Django 3.1.1 on 2020-09-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_driver_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
