# Generated by Django 3.1.1 on 2020-09-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
        ('order', '0002_auto_20200930_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderDetail',
            new_name='OrderDetail',
        ),
    ]
